# Generated by Django 6.0.6 on 2026-06-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='TEMP', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
